<?php
use Lof\BarcodeInventory\Block\Adminhtml\Barcode\MassPrint;
/** @var $block MassPrint*/


$collection = $block->getCollection();
/** @var TYPE_NAME $helper */
$helper = $this->helper('Lof\BarcodeInventory\Helper\Data');
$css = "<style>".$helper->getCss()."</style>";
$html = $block->escapeJs($helper->generatePaperPrint($collection).$css);
?>
<script>
    var print_window = window.open('', 'print', 'status=1,width=700,height=700');
    print_window.document.open();
    print_window.document.write("<?=$html?>");
    print_window.document.close();
    print_window.print();
</script>
