<?php
$blockObj = $block->getLayout()->createBlock('Lof\BarcodeInventory\Block\Adminhtml\Barcode\MassPrint');

$collection = $blockObj->getCollection();
/** @var TYPE_NAME $helper */
$helper = $this->helper('Lof\BarcodeInventory\Helper\Data');
?>
// doan nay se viet lenh download file pdf
<!--<script>-->
<!--    require([-->
<!--        "jquery",-->
<!--        "jquery/ui"-->
<!--    ], function ($) {-->
<!--        var print_window = window.open('', 'print', 'status=1,width=700,height=700');-->
<!--        print_window.document.open();-->
<!--        print_window.document.write(--><?//= $helper->generatePaperPrint($collection) . $helper->getCss()?>//);
<!--//        print_window.document.close();-->
<!--//        print_window.print();-->
<!--//    }-->
<!--//</script>-->
