<div class="image image-placeholder" style="overflow: hidden;">
    <div  class="uploader">
        <div class="fileinput-button form-buttons button">
            <span>Browse Files...</span>
            <input id="file" name="file" type="file">
        </div>
    </div>

    <div class="product-image-wrapper">
        <p class="image-placeholder-text">
            Browse to find or drag csv file here
        </p>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Lof_BarcodeInventory/js/uploadCsv": {
                "uploadUrl": "<?php echo $this->getUploadAjaxUrl() ?>"
            }
        }
    }
</script>